### PR TITLE
Update UBCPI block to work on newer versions of Python.

### PR DESCRIPTION
**Pull request by feanil**

### CODE REVIEW

**Comment by feanil** [comment]
FYI @jmbowman

**Comment by kitsook** [comment]
@feanil Thanks for submitting the PR for Python 3 upgrade.  We revised the UI and changes in the PR need to be revised.  Also, could you advise when should we change https://github.com/edx/configuration/blob/b9aac4be1171e1088e6fdbe0536d4be0a5e02f3b/playbooks/roles/edxapp/defaults/main.yml#L529 for upstream to pick up the new UI with Python 3 upgrade?  Is the devstack ready for Python 3?

**Comment by feanil** [comment]
@kitsook upstream is running on python3 and devstack is as well if you pick up the latest devstack.  I think upstream can be updated as soon as this lands on master.

**Comment by kitsook** [comment]
Closing this PR.  Changes in this request has been merged with the new UI with #173

**Pull request closed without merging**
