### PR TITLE
WL-353 peer instruction tool

### PR DESCRIPTION
**Pull request by asadiqbal08**
Marked the possible strings for translations and created a `translations` directory with empty .po file for `en` language. 
Log a issue [HERE](https://github.com/ubc/ubcpi/issues/79)

### CODE REVIEW

**Comment by asadiqbal08** [comment]
@richardtape I made a commit today [HERE](https://github.com/edx/XBlock/pull/335/files). There is a change in `XBlock` repo. I am sure after this merge we have a grenn build.

**Comment by xcompass** [comment]
Thanks @asadiqbal08. I'll re-run the tests once the PR https://github.com/edx/XBlock/pull/335 is merged.

**Comment by mattdrayer** [comment]
FYI, we can close this PR now that #81 has been submitted -- I had to make some changes to the base XBlock repository and wanted to update the peer instruction tool PR while @asadiqbal08 is on holiday.

**Comment by mattdrayer** [comment]
I guess I can't close this PR myself, because Github doesn't see me as being related in any particular way (hence my need to create my own fork in the first place).  @richardtape or @xcompass -- please freel free to close this PR at your convenience.

**Pull request closed without merging**
