### PR TITLE
Added problem weighting, allowing unit to have a weight >1 in graded subsections 

### PR DESCRIPTION
**Pull request by bpickard**
Added problem weighting, allowing unit to have a weight >1 in graded subsections (#38)
* Added problem weight field to unit settings
* Updated student view with problem weight
* Minor formatting and spelling fixes

### CODE REVIEW

**Comment by sarina** [comment]
@nedbat could you take a look at this? Per https://github.com/edx/edx-platform/pull/10937 there may have been some previous performance concerns around scoring, but I don't remember what those were or who raised them; regardless UBC is wondering if they can add the scoring stuff back in.

**Comment by xcompass** [comment]
@nedbat how's going with this PR? Can we merge it in? Do you have any concern? Thanks.

**Comment by jbarciauskas** [comment]
@xcompass can you find the email with the performance concerns?

**Comment by xcompass** [comment]
@jbarciauskas Just forwarded the email to you.

**Comment by ormsbee** [comment]
:+1:

**Comment by xcompass** [comment]
@bpickard could you squash the change and rebase from new master? Then I'll merge it.

**Comment by xcompass** [comment]
@bpickard never mind. Forgot you are off. I merged it. Thanks.

**Comment by bpickard** [comment]
Thanks @xcompass, I wouldn't have minded anyhow :)

**Pull request merged**
