### PR TITLE
asadiqbal08/WL-408 Dummy eo translations for testing

### PR DESCRIPTION
**Pull request by asadiqbal08**
@mattdrayer @xcompass can you guys please review the change set ?

### CODE REVIEW

**Comment by mattdrayer** [comment]
👍 need to squash commits

**Comment by xcompass** [comment]
:+1:  Looks good.

**Comment by xcompass** [comment]
@asadiqbal08 do you need me to release a new version?

**Comment by mattdrayer** [comment]
That would be great if you could, @xcompass -- I can submit a PR to edx-platform with the new version number when ready.

**Comment by xcompass** [comment]
@mattdrayer Done. 0.5.3 is available on PyPi: https://pypi.python.org/pypi/ubcpi-xblock/0.5.3

**Comment by mattdrayer** [comment]
Great, thanks!

On Thu, Apr 7, 2016 at 2:54 PM, Pan Luo <notifications@github.com> wrote:

> @mattdrayer <https://github.com/mattdrayer> Done. 0.5.3 is available on
> PyPi: https://pypi.python.org/pypi/ubcpi-xblock/0.5.3
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly or view it on GitHub
> <https://github.com/ubc/ubcpi/pull/82#issuecomment-207048762>
>



-- 
Matthew Drayer
Solutions Architect
edX | MIT
mattdrayer@edx.org

**Pull request merged**
